export const participants = [
  { name: "Banana", slug: "banana" },
  { name: "Mega Frango", slug: "mega-frango" },
  { name: "Laelson", slug: "laelson" },
  { name: "Pires", slug: "pires" },
  { name: "Jarrão", slug: "jarrao" },
  { name: "Netico", slug: "netico" },
  { name: "Léo", slug: "leo" },
  { name: "Andrey", slug: "andrey" },
  { name: "Otávio", slug: "otavio" },
  { name: "Luciano", slug: "luciano" },
  { name: "Neto", slug: "neto" },
  { name: "Lalo", slug: "lalo" },
  { name: "Kléber", slug: "kleber" },
  { name: "Lucas", slug: "lucas" },
];
